version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: portfolio-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: portfolio
      MARIADB_USER: portfolio_user
      MARIADB_PASSWORD: portfolio_pass
    ports:
      - "3999:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    container_name: portfolio-backend
    depends_on:
      - mariadb
    ports:
      - "9091:9091"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/portfolio
      SPRING_DATASOURCE_USERNAME: portfolio_user
      SPRING_DATASOURCE_PASSWORD: portfolio_pass
      ADMIN_SESSION_PASSWORD: ${ADMIN_SESSION_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      OTP_SECRET: ${OTP_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}

volumes:
  mysql_data: