version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: portfolio-postgres
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    container_name: portfolio-backend
    depends_on:
      - postgres
    ports:
      - "9091:9091"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portfolio
      SPRING_DATASOURCE_USERNAME: portfolio_user
      SPRING_DATASOURCE_PASSWORD: postgres
      ADMIN_SESSION_PASSWORD: ${ADMIN_SESSION_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      OTP_SECRET: ${OTP_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}

volumes:
  postgres_data: